name: CI
run-name: bar
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello, World!"

  call_reusable_workflow:
    needs: test
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      message: "Hello from the caller workflow!"
      # run-name: "test-run-name"
